version: '2'
services:
  elasticsearch-node1:
    image: elasticsearch:2.3.3
    container_name: es-node1
    environment:
      - NODE_NAME=es-node1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch-node2:
    image: elasticsearch:2.3.3
    container_name: es-node2
    environment:
      - NODE_NAME=es-node2
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
